version: '3'
services:
  server1:
    container_name: server1
    build: ./app
    depends_on:
      - redis
    environment:
      - SERVER_NAME=server1
  server2:
    container_name: server2
    build: ./app
    depends_on:
      - redis
    environment:
      - SERVER_NAME=server2
  redis:
    container_name: cache
    image: redis
  nginx:
    container_name: load-balancer
    image: nginx
    depends_on:
      - server1
      - server2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80