version: '3'
services:
  server-1:
    container_name: server-1
    image: node:alpine
    volumes:
      - /Users/allen/redis-sentinel-poc/app:/var/app
    command: node /var/app/bin/www
    depends_on:
      - redis-node-1
      - redis-node-2
    environment:
      - SERVER_NAME=server-1

  server-2:
    container_name: server-2
    image: node:alpine
    volumes:
      - /Users/allen/redis-sentinel-poc/app:/var/app
    command: node /var/app/bin/www
    depends_on:
      - redis-node-1
      - redis-node-2
    environment:
      - SERVER_NAME=server-2

  redis-node-1:
    container_name: redis-node-1
    image: redis
    ports:
      - 6379:6379

  redis-node-2:
    container_name: redis-node-2
    image: redis
    ports:
      - 6380:6380
    command: redis-server --port 6380
    
  nginx:
    container_name: load-balancer
    image: nginx
    depends_on:
      - server-1
      - server-2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80