version: '3'
services:
  server-1:
    container_name: server-1
    build: ./app
    depends_on:
      - redis-sentinel-1
    environment:
      - SERVER_NAME=server-1

  server-2:
    container_name: server-2
    build: ./app
    depends_on:
      - redis-sentinel-1
    environment:
      - SERVER_NAME=server-2

  redis-master:
    container_name: redis-master
    image: redis

  redis-slave:
    container_name: redis-slave
    image: redis
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  redis-sentinel-1:
    container_name: redis-sentinel-1
    image: redis
    depends_on:
      - redis-slave
    volumes:
      - ./redis-sentinel-1.conf:/etc/nginx/sentinel.conf
    command: redis-server /etc/nginx/sentinel.conf --sentinel --port 26379
    
  nginx:
    container_name: load-balancer
    image: nginx
    depends_on:
      - server-1
      - server-2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80